language: node_js
node_js:
  - "12"
cache:
  directories:
  - node_modules
script:
  - python tester.py
  - npm install
  - ng build --prod --base-href https://cephalonwannab.com/
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: true
    local_dir: dist/tierlist
    on:
        branch: master
notifications:
  email:
    recipients:
      - $NADER_EMAIL
      - $SAKAI_EMAIL
    on_success: never
    on_failure: always
